### ISSUE TITLE
Unfortunately (app name) has stopped :(

### ISSUE THREAD

**Issue by leosonic256** [huzongyao/NostalgiaLite#1]
When I try to emulate a game, the emulator shows me the following error message:
Unfortunately (app name) has stopped

**Comment by huzongyao** [comment]
which emulator? FC?

**Comment by leosonic256** [comment]
NostalgiaLite "NES" I'm using Android Studio with the version of Android 4

**Comment by huzongyao** [comment]
fixed

**Comment by leosonic256** [comment]
It works now. Thank you
